require "fileutils"

module RubocopTodoSplit
  class Writer
    HEADER = "# Auto-generated by rubocop-todo-split. Do not edit manually.\n"

    def initialize(entries, file_header:, output_dir:, dry_run: false)
      @entries = entries
      @file_header = file_header
      @output_dir = output_dir
      @dry_run = dry_run
    end

    def write
      grouped = @entries.group_by(&:department)

      grouped.each_with_object({}) do |(department, entries), result|
        content = build_content(entries)
        path = File.join(@output_dir, "#{department}.yml")
        result[path] = content

        unless @dry_run
          FileUtils.mkdir_p(@output_dir)
          File.write(path, content)
        end
      end
    end

    def update_rubocop_yml(rubocop_path, department_files)
      return unless File.exist?(rubocop_path)

      content = File.read(rubocop_path)
      inherit_lines = department_files.map { |f| "  - #{f}" }.join("\n")
      new_inherit = "inherit_from:\n#{inherit_lines}"

      updated =
        if content.match?(/^inherit_from:/m)
          content.gsub(/^inherit_from:.*?(?=\n\S|\z)/m, new_inherit)
        else
          "#{new_inherit}\n\n#{content}"
        end

      File.write(rubocop_path, updated) unless @dry_run
      updated
    end

    def rewrite_todo_yml(todo_path, department_files)
      regen_cmd = "rubocop --auto-gen-config --exclude-limit 9999 --no-auto-gen-timestamp"
      split_cmd = "rubocop-todo-split"

      stub = <<~YAML
        #{@file_header.join.chomp}

        # This file has been split into per-department files by rubocop-todo-split.
        # Offenses are now tracked in:
        #{department_files.map { |f| "#   #{f}" }.join("\n")}
        #
        # To regenerate after fixing offenses:
        #   #{regen_cmd}
        #   #{split_cmd}
      YAML

      File.write(todo_path, stub) unless @dry_run
      stub
    end

    private

    def build_content(entries)
      lines = [HEADER]
      lines.concat(@file_header) if @file_header&.any?
      entries.each do |entry|
        lines << "\n"
        lines.concat(entry.lines.drop_while { |l| l.strip.empty? })
      end
      lines.join
    end
  end
end
