require "spec_helper"

RSpec.describe RubocopTodoSplit::Parser do
  let(:source) { <<~YAML }
    # This file was auto-generated by RuboCop.
    # using RuboCop version 1.88.0.

    # Offense count: 2
    # Cop supports --autocorrect.
    Style/StringLiterals:
      EnforcedStyle: double_quotes
      Exclude:
        - 'app/models/user.rb'

    # Offense count: 1
    Layout/LineLength:
      Max: 120
      Exclude:
        - 'app/controllers/users_controller.rb'

    Metrics/MethodLength:
      Max: 15
      Exclude:
        - 'lib/complex_service.rb'
  YAML

  subject(:result) { described_class.parse(source) }

  it "returns a ParseResult" do
    expect(result).to be_a(RubocopTodoSplit::ParseResult)
  end

  it "returns one entry per cop" do
    expect(result.entries.size).to eq(3)
  end

  it "sets the department correctly" do
    expect(result.entries.map(&:department)).to eq(%w[Style Layout Metrics])
  end

  it "sets the cop name correctly" do
    expect(result.entries.map(&:cop)).to eq(%w[Style/StringLiterals Layout/LineLength Metrics/MethodLength])
  end

  it "extracts the file header separately" do
    expect(result.file_header.join).to include("This file was auto-generated by RuboCop")
    expect(result.file_header.join).to include("RuboCop version 1.88.0")
  end

  it "does not include the file header in any entry" do
    result.entries.each do |entry|
      expect(entry.lines.join).not_to include("This file was auto-generated by RuboCop")
    end
  end

  it "preserves per-cop comments in entry lines" do
    style_entry = result.entries.find { |e| e.cop == "Style/StringLiterals" }
    expect(style_entry.lines.join).to include("# Offense count: 2")
  end

  it "includes the cop key line in entry lines" do
    style_entry = result.entries.find { |e| e.cop == "Style/StringLiterals" }
    expect(style_entry.lines.join).to include("Style/StringLiterals:")
  end

  it "includes body lines in entry" do
    layout_entry = result.entries.find { |e| e.cop == "Layout/LineLength" }
    expect(layout_entry.lines.join).to include("Max: 120")
    expect(layout_entry.lines.join).to include("users_controller.rb")
  end

  context "with duplicate cops" do
    let(:source) { <<~YAML }
      # Offense count: 1
      Style/StringLiterals:
        Exclude:
          - 'app/old.rb'

      # Offense count: 3
      Style/StringLiterals:
        Exclude:
          - 'app/new.rb'
    YAML

    it "deduplicates, keeping the last occurrence" do
      expect(result.entries.count { |e| e.cop == "Style/StringLiterals" }).to eq(1)
      last = result.entries.find { |e| e.cop == "Style/StringLiterals" }
      expect(last.lines.join).to include("app/new.rb")
      expect(last.lines.join).not_to include("app/old.rb")
    end
  end

  context "with an empty source" do
    subject(:result) { described_class.parse("") }

    it "returns no entries" do
      expect(result.entries).to eq([])
    end

    it "returns an empty file header" do
      expect(result.file_header).to eq([])
    end
  end

  context "with only comments and blank lines" do
    subject(:result) { described_class.parse("# just a comment\n\n") }

    it "returns no entries" do
      expect(result.entries).to eq([])
    end

    it "captures the comment as a file header" do
      expect(result.file_header.join).to include("# just a comment")
    end
  end
end
