require "spec_helper"
require "tmpdir"

RSpec.describe RubocopTodoSplit::Writer do
  let(:file_header) { ["# This file was auto-generated by RuboCop.\n", "# using RuboCop version 1.88.0.\n"] }

  let(:entries) do
    [
      RubocopTodoSplit::Entry.new(
        department: "Style",
        cop: "Style/StringLiterals",
        lines: ["# Offense count: 2\n", "Style/StringLiterals:\n", "  EnforcedStyle: double_quotes\n"]
      ),
      RubocopTodoSplit::Entry.new(
        department: "Style",
        cop: "Style/FrozenStringLiteralComment",
        lines: ["Style/FrozenStringLiteralComment:\n", "  Enabled: false\n"]
      ),
      RubocopTodoSplit::Entry.new(
        department: "Layout",
        cop: "Layout/LineLength",
        lines: ["# Offense count: 1\n", "Layout/LineLength:\n", "  Max: 120\n"]
      )
    ]
  end

  subject(:writer) do
    described_class.new(entries, file_header: file_header, output_dir: tmpdir, dry_run: true)
  end

  let(:tmpdir) { Dir.mktmpdir }
  after { FileUtils.rm_rf(tmpdir) }

  describe "#write (dry_run)" do
    it "returns a hash keyed by output path" do
      result = writer.write
      expect(result.keys.map { |k| File.basename(k) }).to match_array(%w[Style.yml Layout.yml])
    end

    it "does not create files in dry_run mode" do
      writer.write
      expect(Dir.glob(File.join(tmpdir, "*.yml"))).to be_empty
    end

    it "groups multiple cops from the same department into one file" do
      result = writer.write
      style_path = result.keys.find { |k| k.end_with?("Style.yml") }
      expect(result[style_path]).to include("Style/StringLiterals:")
      expect(result[style_path]).to include("Style/FrozenStringLiteralComment:")
    end

    it "includes the auto-generated notice" do
      result = writer.write
      result.each_value do |content|
        expect(content).to include("Auto-generated by rubocop-todo-split")
      end
    end

    it "includes the refresh instruction for the correct department" do
      result = writer.write
      style_path = result.keys.find { |k| k.end_with?("Style.yml") }
      layout_path = result.keys.find { |k| k.end_with?("Layout.yml") }
      expect(result[style_path]).to include("--refresh Style")
      expect(result[layout_path]).to include("--refresh Layout")
    end

    it "preserves per-cop comments" do
      result = writer.write
      style_path = result.keys.find { |k| k.end_with?("Style.yml") }
      expect(result[style_path]).to include("# Offense count: 2")
    end
  end

  describe "#write (not dry_run)" do
    subject(:writing_writer) do
      described_class.new(entries, file_header: file_header, output_dir: tmpdir, dry_run: false)
    end

    it "creates the output files" do
      writing_writer.write
      expect(File.exist?(File.join(tmpdir, "Style.yml"))).to be true
      expect(File.exist?(File.join(tmpdir, "Layout.yml"))).to be true
    end
  end

  describe "#update_rubocop_yml" do
    let(:rubocop_path) { File.join(tmpdir, ".rubocop.yml") }

    context "when .rubocop.yml has no existing inherit_from" do
      before { File.write(rubocop_path, "AllCops:\n  NewCops: enable\n") }

      it "prepends the inherit_from block" do
        content = writer.update_rubocop_yml(rubocop_path, ["rubocop_todo/Style.yml", "rubocop_todo/Layout.yml"])
        expect(content).to include("inherit_from:")
        expect(content).to include("  - rubocop_todo/Style.yml")
      end
    end

    context "when .rubocop.yml already has inherit_from" do
      before do
        File.write(rubocop_path, "inherit_from:\n  - old.yml\n\nAllCops:\n  NewCops: enable\n")
      end

      it "replaces the existing inherit_from block" do
        content = writer.update_rubocop_yml(rubocop_path, ["rubocop_todo/Style.yml"])
        expect(content).not_to include("old.yml")
        expect(content).to include("  - rubocop_todo/Style.yml")
      end
    end
  end

  describe "#rewrite_todo_yml" do
    let(:todo_path) { File.join(tmpdir, ".rubocop_todo.yml") }
    let(:department_files) { ["rubocop_todo/Style.yml", "rubocop_todo/Layout.yml"] }

    before { File.write(todo_path, "original content") }

    it "returns a stub containing the original file header" do
      stub = writer.rewrite_todo_yml(todo_path, department_files)
      expect(stub).to include("This file was auto-generated by RuboCop")
    end

    it "lists the department files" do
      stub = writer.rewrite_todo_yml(todo_path, department_files)
      expect(stub).to include("rubocop_todo/Style.yml")
      expect(stub).to include("rubocop_todo/Layout.yml")
    end

    it "includes regeneration instructions" do
      stub = writer.rewrite_todo_yml(todo_path, department_files)
      expect(stub).to include("rubocop-todo-split --regenerate")
      expect(stub).to include("rubocop-todo-split --refresh Layout")
    end

    it "does not write the file in dry_run mode" do
      writer.rewrite_todo_yml(todo_path, department_files)
      expect(File.read(todo_path)).to eq("original content")
    end
  end
end
